export const VEHICLE = {
  MASS: 650,
  STEER: 0.5,
  FORCE: 1800,
  MAX_BRAKE: 45,
  MAX_SPEED: 60,
  MAX_SPEED_BOOST: 107,
  TURBO_PER_SECOND: 4,
  TURBO_MAX: 15,
  TURBO_DISPLAY_TIME: 0.5,
  DRIFT_MIN_SPEED: 15,
  ANGULAR_DAMPING: 0.39,
  YAW_TORQUE: 300,
  YAW_TORQUE_DRIFT: 1300,
  HANDBRAKE_KICK: 8,
} as const;

export const WHEEL = {
  RADIUS: 0.2,
  WIDTH: 0.15,
  FRONT_Z: 0.8,
  BACK_Z: -0.8,
  SIDE_X: 0.65,
  HEIGHT_Y: -0.15,
  SUSPENSION_STIFFNESS: 30,
  SUSPENSION_REST_LENGTH: 0.35,
  FRICTION_SLIP: 0.9,
  ROLL_INFLUENCE: 0.25,
  SIDE_ACCELERATION: 2.9,
} as const;

export const SCORING = {
  MIN_DRIFT_ANGLE: 0.12,
  POINTS_PER_SECOND: 100,
  SPEED_MULTIPLIER: 2,
  COMBO_INTERVAL: 3,
  COMBO_INCREMENT: 0.5,
  MAX_COMBO: 5,
  ROUND_DURATION: 60,
} as const;

export const TRACK = {
  LOT_WIDTH: 80,
  LOT_LENGTH: 120,
  WALL_HEIGHT: 1.2,
  WALL_THICKNESS: 0.5,
  START_X: 0,
  START_Z: -40,
} as const;

export const CAMERA = {
  DRIFT_LATERAL_MAX: 4,
} as const;
